### ISSUE TITLE
Table "Piedone_Combinator_CombinedFileRecord" is locked in sql server

### ISSUE THREAD

**Issue by privateField** [Lombiq/Combinator#11]
We are permanently getting a table locked after the first request. Every next request receives a timeout error and nothing is minified.

To resolve this issue we did next changes in CacheFileService.cs in the Save() method:

``` c#
            ...
                LastUpdatedUtc = resource.LastUpdatedUtc,
                Settings = _combinatorResourceManager.SerializeResourceSettings(resource)
            };

           _transactionManager.GetSession().Transaction.Begin();
           _fileRepository.Create(fileRecord);
           _fileRepository.Flush();
           _transactionManager.GetSession().Transaction.Commit();
```

**Comment by Piedone** [comment]
So you added the `Transaction.Begin()` and `Transaction.Commit()`, right?

Interesting, never had this issue and I don't know why the lock would just remain there (I could understand that if you have a lot of concurrent request while there is nothing processed by Combinator yet then some requests' such queries will time out, but that would heal).

Can you tell a bit more about your environment? Do you use a standard SQL Server or something else? Does this happen even if you issue requests one by one, waiting for the previous to finish?

**Comment by privateField** [comment]
Right, we just added  `Transaction.Begin()` and `Transaction.Commit()`.
We currently using Sql Server 2008 R2, this is a test environment so the website is not under high load.
We have a lot of resources to be minified and compressed (about 100 css+js files). Output is 2 style files and 1 script file.
I understand that Orchard creates a transaction per each request, so `_fileRepository.Create(fileRecord);` should be done with Orchard's transaction commit, but somehow this transaction not finishes with commit (or with rollback). Do you know the reasons why Orchard's transaction may not close?

**Comment by Piedone** [comment]
I see, the amount of files shouldn't be a problem since this method only runs once for each processed resource - so three times in a request for you.

Now it _might_ have to do something with how long the request takes, which can be significant with that many files being processed: can you tell some measurements? Because it can be that the handle to the DB server times out, though the symptoms aren't conclusive for me on this either.

And yes, you understand correctly so yes, the transaction should close automatically. However... There was an issue on earlier Orchard versions with the NHibernate session not being disposed properly, so that might be affecting you. I don't know the precise version but it was before 1.9. So if you use an Orchard version before 1.9 than I think you are affected and that can be behind the issue you're seeing.

**Comment by Piedone** [comment]
BTW every project where I've seen Combinator uses SQL Server 2012 or later, but that shouldn't make a difference.

**Comment by Piedone** [comment]
Assuming it was due to the mentioned bug in previous Orchard versions. Please come back if you have more info.
