### ISSUE TITLE
Extra phantom module listed in admin page

### ISSUE THREAD

**Issue by rtpHarry** [Lombiq/Combinator#16]
Orchard 1.9.2.0
Combinator download from master branch as zip, extracted to folder with the `-master` removed from end
Helpful Lib same as above

![image](https://cloud.githubusercontent.com/assets/1038062/16361765/8f1fb8d8-3b92-11e6-8c7d-3999e0e22127.png)

Shows the two libraries at the top so I thought they were the correct ones but then I saw no dependency listed.

If I filter the view it shows the proper one in its proper place:

![image](https://cloud.githubusercontent.com/assets/1038062/16361772/b4e580fc-3b92-11e6-824f-e0f96e228bc5.png)

**Comment by Piedone** [comment]
That's interesting... Did you put the module in a folder called Piedone.Cominator?

**Comment by rtpHarry** [comment]
no i didnt have `piedone.` prefix. Deleted the lot, made two new prefixed dirs and extracted the download master.zips into each. The combinator one went away but still got the helpful libraries one. 

I've just scrapped it now and gone to the gallery tab and attempting to install that way instead.

**Comment by rtpHarry** [comment]
I expect this was just me doing something wrong? Feel free to close if you don't see any value in pursuing further :)

**Comment by Piedone** [comment]
Extensions should always be placed in a folder that that has the same name as the extension's ID (which equals to the project file name). Otherwise you can get such issues (and also later module loading problem, so e.g. when you seemingly enable the module it won't really work because Orchard won't be able to find it).

So yes, I don't think this is a problem with either module :-).

Though please don't use the Gallery versions, haven't updated them in ages... Downloading from GitHub (or using them as submodules/repos) is the way to go at the moment.
