### ISSUE TITLE
Clustered sites behind load balancer

### ISSUE THREAD

**Issue by Tovli** [Lombiq/Combinator#19]
Hi,
We have one DB for all 4 sites that we have which are behind a load balancer, and its causing us some issues because each time we are doing some changes (js, css) we need to copy the minified combinator files from one environment  to other 3.
The problem with this method is that we can have situations when during testing we didn’t access some page or state of the page, and combinator didn’t generate the minified files for it, in this case after copying the files to other 3 environments we will not have all the minified files from combinator that we need.

Is there a solution for this?

**Comment by Piedone** [comment]
In such a case you need to make the Media storage shared too (e.g. with Azure Blob Storage). Since Combinator stores files in the Media folder this will solve this issue too (and you need shared Media anyways, otherwise Media management will break too).

If you need more help with multi-node scenarios, [get in touch with us at Lombiq](https://lombiq.com/contact-us), we have done a lot on that matter.
